# Generated by Django 5.2.5 on 2025-08-27 00:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=128)),
            ],
            options={
                'verbose_name': 'Payment_Method',
                'verbose_name_plural': 'Payment_Methods',
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('function', models.CharField(db_column='tx_function', max_length=40)),
                ('max_salary', models.DecimalField(db_column='nb_max_salary', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_salary', models.DecimalField(db_column='nb_min_salary', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('daily_rate', models.DecimalField(db_column='nb_daily_rate', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.IntegerField(db_column='nb_capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('type_room', models.IntegerField(choices=[(1, 'Suite'), (2, 'Normal'), (3, 'Premium')], db_column='cs_room_type', default=2)),
                ('description', models.TextField(db_column='tx_description', max_length=255)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('salary', models.DecimalField(db_column='nb_salary', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.IntegerField(db_column='nb_level', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(db_column='id_position', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('daily_value', models.DecimalField(db_column='nb_daily_value', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(db_column='nb_total_value', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dt_begin', models.DateField(db_column='dt_begin')),
                ('dt_end', models.DateField(db_column='dt_end')),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.room')),
            ],
            options={
                'verbose_name': 'Reservations',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('total_payment', models.DecimalField(db_column='nb_total_payment', decimal_places=2, max_digits=10)),
                ('type', models.IntegerField(choices=[(1, 'Hosting'), (2, 'Service')], db_column='cs_type', default=1)),
                ('discount', models.DecimalField(db_column='nb_discount', decimal_places=2, default=0, max_digits=10)),
                ('value_payment', models.DecimalField(db_column='nb_value_payment', decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.employee')),
                ('payment_method', models.ForeignKey(db_column='id_payment_method', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.paymentmethod')),
                ('reservation', models.ForeignKey(db_column='id_reservation', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.reservation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('type', models.IntegerField(choices=[(1, 'Checkin'), (2, 'Checkout')], db_column='cs_type', default=1)),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='core.employee')),
                ('reservation', models.ForeignKey(db_column='id_reservation', on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='core.reservation')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
                'db_table': 'check',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('type', models.IntegerField(choices=[(1, 'Upgrade Suite'), (2, 'Breakfast'), (3, 'Bar'), (4, 'Restaurant'), (5, 'Room Service'), (6, 'Parking'), (7, 'Transfer'), (8, 'Spa'), (9, 'Recreation'), (10, 'Other')], db_column='cs_type', default=10)),
                ('value', models.DecimalField(db_column='nb_value', decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, db_column='tx_description', max_length=240, null=True)),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.employee')),
                ('reservation', models.ForeignKey(db_column='id_reservation', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.reservation')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
    ]
