# Generated by Django 5.2.5 on 2025-09-18 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='daily_value',
            field=models.DecimalField(blank=True, db_column='nb_daily_value', decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_value',
            field=models.DecimalField(blank=True, db_column='nb_total_value', decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
